aesiniath/unbeliever

lib/Core/Program/Context.hs
Refactoring over the last few days left the handling of log level arguments in an inconsistent state. Fixed.
=> Fix handling of --verbose and --debug

bench/GeneralPerformance.hs, lib/Core/Encoding/Json.hs, lib/Core/Program/Context.hs, lib/Core/Program/Execute.hs, lib/Core/Program/Logging.hs, lib/Core/Program/Signal.hs, lib/Core/Text/Bytes.hs, lib/Core/Text/Rope.hs, package.yaml, tests/SimpleExperiment.hs
Finally end the experiment with multiple constructors for different kinds of underlying sources of bytes, instead delegating conversion to a typeclass Binary the same way Rope delegates to Textual.
Improve documentation somewhat.
Rename `hOutput` in Rope to `hWrite`, matching the "write" name pattern in the Program monad and freeing up the "output" name pattern to be used in Bytes as it already was in Program.
=> Finish bytes

lib/Core/Program/Execute.hs, lib/Core/System/Base.hs, package.yaml
Expose `withContext` which provides a function that can be used within an lifted IO block to return back (unlift?) to the Program monad.
=> Function to unlift from IO back to Program

lib/Core/Program/Arguments.hs, lib/Core/Program/Execute.hs, lib/Core/Text/Utilities.hs, package.yaml
Add
* `lookupOptionsFlag`,
* `lookupOptionsValue`, and
* `lookupArgument`
trialling out actually _using_ the result of loading a program with a command-line Config.
=> Utility functions for handling parsed command-line parameters

lib/Core/Program/Arguments.hs, package.yaml, stack.yaml, tests/CheckArgumentsParsing.hs, tests/CheckProgramMonad.hs, tests/ComplexExperiment.hs, tests/SimpleExperiment.hs
Overload use of ParameterValue type to indicate in an Option declaration whether a parameter expects a value, and if so what label to use for it in the generated `--help` output.
=> Specify labels for options that take values

lib/Core/Program/Arguments.hs, lib/Core/Program/Context.hs, lib/Core/Program/Execute.hs, package.yaml, tests/CheckProgramMonad.hs, tests/ComplexExperiment.hs, tests/SimpleExperiment.hs
In order to support a built-in `--version` option, we need to know the program's version number. We get the author to supply that using the `configure` function at the beginning of the program by requiring version to be supplied to `configure`.
Signature change bumps major API version to 0.6.
=> Specify program version number when configuring.

README.markdown, lib/Core/Data/Structures.hs, lib/Core/Program/Execute.hs, lib/Core/Program/Logging.hs, package.yaml, tests/Snippet.hs
Resolve a race condition that occurred. Numerous problems:
1. Exceptions were being thrown to logging/output thread rather than at call site if a lazy value that resulted in an exception was passed in. Resolve that with `evaluate` and `!` in `write` and friends.
2. Exception thrown in logging/output handler resulted in its collapse. Resolve this by hard-terminating the program if a logging/output thread dies prematurely.
3. The code allowing time to drain the queues at shutdown was looping forever because there was no longer anything to drain the queues. Resolve this with a timeout implemented using `race_`
=> Guard against collapse of logging and output threads

CHANGELOG.markdown, lib/Core/Program/Execute.hs, lib/Core/Program/Logging.hs, lib/Core/Text/Rope.hs, package.yaml
The `write` actions for doing output fit better as a family with `event` and the `debug` actions. Move them from Core.Program.Execute to Core.Program.Logging, and write a description of our approach to output management in the module header.
=> Move write functions to Core.Program.Logging

lib/Core/Text/Rope.hs
We do a lot of (what turns out to be)
```haskell
text <> emptyRope
```
as we fold through various structures. It would be preferable not to grow the fingertree unnecessarily.
=> Minor optimization for when appending empty Ropes

lib/Core/Text/Utilities.hs
This appears to work. Ideally, we could also have an
```haskell
instance Render String
```
rather than relying on an instance for `Char` and an instance for `[a]` because it would make the documentation better. But leads to Overlapping Instance errors. Not to be.
=> List instance for Render

lib/Core/Program/Execute.hs, lib/Core/Program/Metadata.hs, lib/Core/System/Base.hs, lib/Core/Text/Bytes.hs, package.yaml
For some time depending directly on the **Cabal** package has been problematic. It's very heavy weight, and was causing trouble with links in Haddock due to some massive re-exports of everything in Prelude. Remove the use of the proper _.cabal_ file parser and do something simple and brute force to get the few fields we're interested in out.
=> Remove Cabal dependency

lib/Core/Program/Execute.hs, package.yaml
Work around the problem that some VMs (ie that used by Docker-for-Mac) don't seem to carry a modern locale, resulting in crashing programs if anyone outputs a character greater than \xFF. Jeesh.
This was motivated by a user of **publsh** encountering a `commitAndReleaseBuffer: invalid argument (invalid character)` crash when having the temerity to try rendering a document that had a unicode character in it. See https://github.com/oprdyn/publish/issues/32. They're specific setup was running under Docker-for-Mac; I infer that VM doesn't have a proper Unicode locale present.
This patch fixes a Program by forcing the locale to UTF-8 when `execute` is first called.
=> Force the locale of a running Program to be UTF-8

lib/Core/Program/Metadata.hs, lib/Core/Text/Breaking.hs, lib/Core/Text/Rope.hs, lib/Core/Text/Utilities.hs, package.yaml, tests/CheckRopeBehaviour.hs
Breaking behaviour was wrong for both `breakWords` and `breakLines`. Resolve this in new underlying `intoChunks` and `intoPieces` functions.
=> Fix breaking behaviour

core-program/lib/Core/System.hs, core-program/lib/Core/System/Pretty.hs, core-program/package.yaml, core-text/lib/Core/Text/Utilities.hs, core-text/package.yaml, stack.yaml
Having to import the combinators used commonly from **prettyprinter** if you're trying to build a Render instance gets a bit tedious especially if you are explicitly listing the functions you are importing.
=> Re-export pretty prining and combinators for convenience

core-text/lib/Core/Text/Rope.hs, core-text/package.yaml, package.yaml, tests/CheckRopeBehaviour.hs
By changing to `foldl` we are able to leverage the underlying Hashable instance of the ShortByteString backing the ShortText which are the underlying units in the FingerTree backing Rope.
=> Fix Hashable instance for Rope

core-program/lib/Core/System/Pretty.hs, core-text/lib/Core/Text/Breaking.hs, core-text/lib/Core/Text/Parsing.hs, core-text/lib/Core/Text/Rope.hs, core-text/lib/Core/Text/Utilities.hs, core-text/package.yaml, package.yaml, stack.yaml, tests/CheckRopeBehaviour.hs, tests/TestSuite.hs
When doing parsing (and reporting error messages resulting from parse failure) we need to be able to indicate the position within the file (ie Rope representing the input).
=> Utility function to calculate lines and columns

core-program/lib/Core/Program/Arguments.hs, core-program/package.yaml
Fix handling the `Complex` case of Config so that "global" options are handed before probing for the presence of an obligatory command name. This allows the logic already in place checking for `--version`, `--help`, etc to be used before bombing out complaining no command mode was specified.
Resolves #38
=> Resolve --version not working on complex command-lines

core-program/lib/Core/Program/Context.hs, core-program/package.yaml, package.yaml, stack.yaml
Add `fmapContext` for the Context type and a Functor instance thereof.
As commented in the code, I would happily accept critique as to whether this is safe or not. I think so? The only way to get to the underlying top-level application data is through `getApplicationState` which is in Program monad so the fact that it is implemented within an MVar should be irrelevant.
=> Fmap context

core-data/lib/Core/Data.hs, core-data/lib/Core/Data/Structures.hs, core-data/lib/Core/Encoding.hs, core-data/lib/Core/Encoding/Json.hs, core-data/package.yaml, core-program/lib/Core/Program/Arguments.hs, core-program/lib/Core/Program/Context.hs, core-program/lib/Core/Program/Execute.hs, core-program/lib/Core/Program/Logging.hs, core-program/lib/Core/Program/Metadata.hs, core-program/lib/Core/Program/Notify.hs, core-program/lib/Core/Program/Signal.hs, core-program/lib/Core/Program/Unlift.hs, core-program/lib/Core/System/Base.hs, core-program/lib/Core/System/External.hs, core-program/lib/Core/System/Pretty.hs, core-program/package.yaml, core-text/lib/Core/Text/Breaking.hs, core-text/lib/Core/Text/Bytes.hs, core-text/lib/Core/Text/Parsing.hs, core-text/lib/Core/Text/Rope.hs, core-text/lib/Core/Text/Utilities.hs, core-text/package.yaml, package.yaml, stack.yaml
The obvious change it to indentation of four spaces, but a more subtle (but highly prized) change is **fourmolu**'s support for multi-line haddock blocks. We used these extensively to differentiate documentation from code comments and it's terrific to recover this capability.
=> Format code with Fourmolu

core-program/lib/Core/Program/Context.hs, core-program/lib/Core/Program/Execute.hs, core-program/lib/Core/Program/Logging.hs, core-program/package.yaml, stack.yaml, tests/SimpleExperiment.hs
Enable resetting the elapsed timer shown in log messages by adding new function `resetTimer` in the Program monad.
Change the precision in log messages to (00.000); there really isn't a need for 5 digits of seconds but, on reflection, keeping milliseconds is nice.
=> Allow timer reset

LICENSE, core-data/package.yaml, core-program/lib/Core/Program/Execute.hs, core-program/package.yaml, core-text/lib/Core/Text/Bytes.hs, core-text/lib/Core/Text/Rope.hs, core-text/package.yaml, package.yaml, stack.yaml
The ergonomics of creating a Bytes from a string literal in code were getting a bit tedious, so add `packBytes` taking a String.
=> Minor improvements to Bytes type

core-text/lib/Core/Text/Rope.hs, core-text/package.yaml, package.yaml, tests/CheckRopeBehaviour.hs
This would probably admit a more efficient implementation, but for as the **fingertree** documentation points out `take` is just a special case of `search`, which is what powers `splitRope`. So using that lazily should give us about the same thing anyway.
=> Implement takeRope function

core-program/core-program.cabal, core-program/lib/Core/Program/Context.hs, core-program/package.yaml
Derive a MonadMask instance so that `bracket` can be used when working in the Program monad. It also turns out we can derive MonadCatch (that powers `catch`) rather than the hand written instance we had preivously.
=> Enable use of bracket from Program monad

core-program/core-program.cabal, core-program/lib/Core/Program/Execute.hs, core-program/package.yaml, stack.yaml
The exception handling logic was severly lacking, and had what appear too be if not race conditions then severe inconsistencies. Resolve by not using catches _inside_ `async`, but instead letting **async** do it's own thing with exceptions (which it needs to do with AsyncCancelled for managing threads); notably, refactor to use `race` instead.
Simplify `executionAction` by removing it and calling `subProgram` directly inline.
=> Fix exception handling

core-program/core-program.cabal, core-program/lib/Core/Program/Execute.hs, core-program/package.yaml
For use in `forever` loops, introduce `trap_` to catch all exceptions and log them.
=> Add function to trap uncaught exceptions

.gitignore, core-program/core-program.cabal, core-program/lib/Core/Program/Arguments.hs, core-program/lib/Core/Program/Execute.hs, core-program/lib/Core/Program/Logging.hs, core-program/package.yaml, core-telemetry/core-telemetry.cabal, core-text/core-text.cabal, core-text/lib/Core/Text.hs, core-text/lib/Core/Text/Colour.hs, core-text/lib/Core/Text/Utilities.hs, core-text/package.yaml
"events" turn out to be the vocabulary in observability systems like Honeycomb (and to a lesser extent OpenTelemetry) whereas calling `event` was about these are local log messages. So {shrug} go with the terminology that's been around for years, and change to `info`.
=> Rename event action to info

core-program/lib/Core/Program/Context.hs, core-program/lib/Core/Program/Execute.hs, core-program/lib/Core/Program/Logging.hs, core-program/lib/Core/Program/Signal.hs, tests/SimpleExperiment.hs
Introduce `warn` and `critical` logging actions to complement `info`, and give them distinctive colours when output.
Document the toggling behaviour of sending SIGUSR1 to a **core-program** program.
Begin removing mention of a separate duplicate logging channel. Logs are to `stdout`.
=> Add warning- and critical-level informational message actions

tests/CheckProgramMonad.hs
Staggering re-write, brilliant thought leadership, truly blinding, titanic 10x engineer prowess.
No but seriously:
`ghcid` had a nit about one of the test files. This is the fix.
=> Fix a ghcid nit.

core-program/core-program.cabal, core-program/lib/Core/Program/Execute.hs, core-program/lib/Core/Program/Logging.hs, core-program/package.yaml, core-telemetry/lib/Core/Telemetry/Observability.hs
To improve the ergonomics of working with command-line parameters, change the lookup functions to actions in the Program monad, following the naming convention `query*`. Simplify the return types so that the unnecessary Maybe wrappers are no longer exposed.
=> Expose parameter lookups as query actions

core-program/core-program.cabal, core-program/lib/Core/Program/Arguments.hs, core-program/lib/Core/Program/Execute.hs, core-program/package.yaml
There are different conventions out there, but one has the options and arguments surrounded by < and > to indicate the variable nature (as opposed to a compulsory string). Adapt to that here.
=> Tweak help output of option values and arguments

core-program/core-program.cabal, core-program/lib/Core/Program.hs, core-program/lib/Core/Program/Execute.hs, core-program/lib/Core/Program/Threads.hs, core-program/package.yaml
Move `forkThread`, `waitThread` and new functions wrapping `concurrently` and `race` to new module Core.Program.Threads. This triggers a major API bump for **core-program**, though largely isn't a breaking change if people are importing Core.Program like is recommended by the documentation.
This sets up for a more comprehensive treatment of general concurrency.
=> Separate thread functions into new module

core-program/core-program.cabal, core-program/lib/Core/Program/Context.hs, core-program/lib/Core/Program/Metadata.hs, core-program/package.yaml, tests/CheckProgramMonad.hs
Expose the current source location as the symbol `__LOCATION__`.
This name was chosen to make in reminiscent of the values you can get from using the CPP extension in Haskell and other languages, but as noted in the code
> This works because the call stack has the most recent frame at the head of the list. Huge credit to @parsonsmatt for having pointed out this technique at <https://twitter.com/mattoflambda/status/1460769133923028995>
it does not actually require CPP! Amazing.
Add a Render instance to simply format the file and line number as 
```
tests/Snippet:32
```
if you need more you've got the SrcLoc, and if you need the stack trace, well, you access `callStack`. Very cool.
=> Access source location metadata without requiring TemplateHaskell

core-data/lib/Core/Data/Structures.hs
Solve some `ghcid` lint warnings the old-fashioned way.
=> Silence the redundant constraints lint warning for this file

core-program/lib/Core/Program/Context.hs, core-telemetry/core-telemetry.cabal, core-telemetry/lib/Core/Telemetry/Identifiers.hs, core-telemetry/lib/Core/Telemetry/Observability.hs, core-telemetry/package.yaml, package.yaml, tests/CheckProgramMonad.hs, tests/CheckTelemetryMachinery.hs, unbeliever.cabal
Switch to generating trace and span identifiers in hexidecimal form, meeting requirements of the "traceparent" header from the W3C Trace Context Specification.
Closes #96.
=> Emit trace and span identifiers per W3C Trace Context

core-telemetry/core-telemetry.cabal, core-telemetry/lib/Core/Telemetry.hs, core-telemetry/lib/Core/Telemetry/Identifiers.hs, core-telemetry/lib/Core/Telemetry/Observability.hs, core-telemetry/package.yaml, tests/CheckTelemetryMachinery.hs
Add getters to enable you to get at the current Trace and Span identifier lurking in the Program monad's context.
=> Expose identifiers

core-program/lib/Core/Program/Execute.hs, core-webserver-servant/lib/Core/Webserver/Servant.hs
We use these elsewhere in the library system, so it feels a bit silly not to just re-export them here.
=> Add some useful functions from safe-exceptions

core-program/core-program.cabal, core-program/lib/Core/Program/Threads.hs, core-program/package.yaml
Closes #102.
Credit to @carlosdagos for recognizing that the problem was that the `Async.wait` was being cancelled, but that this AsyncCancelled was not being propagated to the child thread. Fixed by having `waitThreads` catch this exception and cancel the thread being waited on in turn. 
Clarify the documentation of behaviour of `forkThread` and `waitThread` in regard to what happens when exceptions are thrown.
=> Fix behaviour of leaking child threads when nesting

core-program/core-program.cabal, core-program/lib/Core/Program/Context.hs, core-program/lib/Core/Program/Execute.hs, core-program/lib/Core/Program/Logging.hs, core-program/package.yaml, core-telemetry/lib/Core/Telemetry/Console.hs, package.yaml, unbeliever.cabal
We ran into a problem that some log aggregating services don't deal with (ie, don't strip) ANSI escape sequences resulting in quite an amount of gibberish obscuring the output. This was particularly a problem with AWS CloudWatch, so much so that (somewhat reluctantly) we'll add the usual trick of detecting whether the sddout handle is a terminal and deciding whether to colour or not based on that.
=> Only colour log output if attached to a terminal

core-data/core-data.cabal, core-data/lib/Core/Encoding/Json.hs, core-data/package.yaml
Ideally we wouldn't need this anywhere but people do keep asking for it and we have the relevant symbols imported in Core.Encoding.Json. So, fine. Add a FromJSON instance for Rope.
=> Add FromJSON instance

core-telemetry/core-telemetry.cabal, core-telemetry/lib/Core/Telemetry/Observability.hs, core-telemetry/package.yaml
When executing a sub Program nested in `encloseSpan` we need to ensure that telemetry is still sent even if an exception is thrown.
=> Ensure a span is sent if an exception is thrown

core-program/core-program.cabal, core-program/lib/Core/Program/Arguments.hs, core-program/package.yaml, tests/ComplexExperiment.hs
If `Variable` entries are present in the Options, include their descriptions in the help output.
Closes #71.
=> Output known environment variables  

core-data/core-data.cabal, core-data/lib/Core/Encoding/Json.hs, core-data/package.yaml, tests/CheckJsonWrapper.hs
When preparing strings to be sent as JSON, escape `\` characters in addition to `"` characters, doing backslashes first.
Fixes #111.
=> Escape backslashes in addition to quotes

core-data/core-data.cabal, core-data/lib/Core/Encoding/Json.hs, core-data/package.yaml, core-program/lib/Core/Program/Metadata.hs, core-text/core-text.cabal, core-text/lib/Core/Text/Breaking.hs, core-text/lib/Core/Text/Rope.hs, core-text/lib/Core/Text/Utilities.hs, core-text/package.yaml
Implement `unconsRope` and `breakRope` so that we can properly scan across a piece of text.
Fix up the JSON string escaping function to be _actually_ compliant with the JSON specification.
=> Fix json escaping again

core-program/core-program.cabal, core-program/lib/Core/Program/Metadata.hs, core-program/package.yaml, core-telemetry/core-telemetry.cabal, core-telemetry/package.yaml, core-text/core-text.cabal, core-text/lib/Core/Text/Rope.hs, core-text/package.yaml
Adapt **core-program** to fix reading .cabal files to use new `breakRope`.
Bump dependencies on **core-data** in order to pick up the fix to JSON string encoding.
=> Fix reading metadata from .cabal files

core-telemetry/core-telemetry.cabal, core-telemetry/lib/Core/Telemetry/Identifiers.hs, core-telemetry/lib/Core/Telemetry/Observability.hs, core-telemetry/package.yaml, core-webserver-warp/core-webserver-warp.cabal, core-webserver-warp/lib/Core/Webserver/Warp.hs, core-webserver-warp/package.yaml
Use the `traceparent:` header to set parent Trace and Span if they are present in an incoming HTTP request.
=> Use traceparent header to set parent trace and span

core-program/core-program.cabal, core-program/lib/Core/Program/Context.hs, core-program/lib/Core/Program/Execute.hs, core-program/lib/Core/Program/Logging.hs, core-program/package.yaml, core-telemetry/core-telemetry.cabal, core-telemetry/lib/Core/Telemetry/Observability.hs, core-telemetry/package.yaml, package.yaml, tests/WarpSnippet.hs, unbeliever.cabal
Create new level `Internal` level for Verbosity and undocumented feature `--debug=internal` to get at it. The messages about traces and spans were already using an `isInternal` helper; now they have an explicit level to go with it.
Emit an "Enter" and "Leave" around spans, and likewise note "Begin" or "Using" when starting a trace.
=> Adjust logging of telemetry

core-telemetry/core-telemetry.cabal, core-telemetry/lib/Core/Telemetry/Observability.hs, core-telemetry/package.yaml
Ensure an empty metric field name is not used with `telemetry` or `sendEvent`.
Closes #83
=> Prohibit empty metric field names

core-program/core-program.cabal, core-program/lib/Core/Program/Arguments.hs, core-program/lib/Core/Program/Signal.hs, core-program/package.yaml
Looks like we had `appendOption` wrong which didn't matter for argument processing but was messing up the display of `--help` output. Fixed.
=> Fix argument order

core-webserver-servant/core-webserver-servant.cabal, core-webserver-servant/lib/Core/Webserver/Servant.hs, core-webserver-servant/package.yaml, stack.yaml
Implement `prepareRoutesWithContext` to align with **servant**'s `serveWithContext`. Required for **servant-auth**.
=> Add context to prepareRoutes for servant-auth

core-program/lib/Core/Program/Arguments.hs, core-program/lib/Core/Program/Execute.hs, core-program/lib/Core/Program/Logging.hs, core-program/lib/Core/Program/Metadata.hs, core-program/lib/Core/Program/Threads.hs, core-program/lib/Core/Program/Unlift.hs, core-program/lib/Core/System/Pretty.hs
Realized a large number of the Haddock hyperlinks were incorrect or had atrophied through renames. Finally worked out how to read the warning output from the `stack haddock` command and do something about it.
=> Fix Haddock links

core-telemetry/package.yaml, core-webserver-warp/lib/Core/Webserver/Warp.hs
It turned out we weren't sending `response.status_code` to the telemetry channel when an error was encountered. We sent `error` but not the HTTP 500 or whatever.
Also, we were sending it as a string, and while Honeycomb seems to allows that, other specs want it numeric and so make both the normal path and the error path both report the metric as a number.
=> When sending errors include HTTP status code

core-telemetry/core-telemetry.cabal, core-telemetry/lib/Core/Telemetry/Observability.hs, core-telemetry/package.yaml
I added a function, so minor version bump is at hand.
I decided _not_ to fold this function in to existing code, as it's deliberately disrespecting the cascade path that Unbeliever set up.
Besides, having all the fields of `Datum` broken out like this would _add_ noise, rather than reduce it.
=> Add ability to send a span in isolation

core-telemetry/core-telemetry.cabal, core-telemetry/lib/Core/Telemetry/Identifiers.hs, core-telemetry/lib/Core/Telemetry/Observability.hs, core-telemetry/package.yaml
Presents an alternative API to that suggested by https://github.com/aesiniath/unbeliever/pull/125. The idea here is that we would create a trace but without specifying the parent, using a new `usingTrace'` function. Then we would re-use the existing `encloseSpan` function augmented by a new override `setIdentifierSpan` function, resulting in a shape like this:
```haskell
usingTrace' trace $ do
encloseSpan "Eat your vegetables" $ do
setStartTime start 
setIdentifierSpan predetermined
telemetry
[ metric "sugar" False
]
```
where `trace` and `predetermined` are the received and already created Trace and Span identifiers, respectively.
While not quite as compact as the `sendSpan` idea proposed by @TheWizardTower, I'd like to suggest that by reusing existing `encloseSpan` machinery we keep the …
=> Create root spans allowing for override of Span identifier

core-webserver-warp/core-webserver-warp.cabal, core-webserver-warp/lib/Core/Webserver/Warp.hs, core-webserver-warp/package.yaml
Including the query string in the "`request.path`" telemetry field was a mistake. We need to separate them out as "`request.query`" if present. This results in the span "`name`" and `"request.path`" being the same value, but that's fine. Allows proper use of the Route field on the Honeycomb home screen.
=> Refine HTTP request fields in telemetry

core-telemetry/core-telemetry.cabal, core-telemetry/lib/Core/Telemetry/Observability.hs, core-telemetry/package.yaml, core-webserver-warp/core-webserver-warp.cabal, core-webserver-warp/lib/Core/Webserver/Warp.hs, core-webserver-warp/package.yaml
@TheWizardTower as discussed, we probably shouldn't be sending `""` if there's no query string component to the URL. Testing shows that Honeycomb hides/ignores/drops fields with JSON `null` as the value, so this seems to accomplish the trick.
=> Only send query string value if present

core-program/core-program.cabal, core-program/lib/Core/Program.hs, core-program/lib/Core/Program/Context.hs, core-program/lib/Core/Program/Exceptions.hs, core-program/lib/Core/Program/Execute.hs, core-program/lib/Core/Program/Threads.hs, core-program/lib/Core/System/Base.hs, core-program/package.yaml, core-telemetry/core-telemetry.cabal, core-telemetry/lib/Core/Telemetry/Honeycomb.hs, core-telemetry/package.yaml, core-webserver-servant/core-webserver-servant.cabal, core-webserver-servant/lib/Core/Webserver/Servant.hs, core-webserver-servant/package.yaml, package.yaml, unbeliever.cabal
The documentation for `catch`, `try`, `throw`, etc coming out of **safe-exception** is quite anemic; it just says "go read the one in **exception**, which then says "like **base** but...". None of this is helpful for an experienced developer and for a beginner it is utterly impenetrable.
This branch creates wrappers for the exception functions specialized to the Program τ monad, meaning that in most cases a user of this library would no longer need to import Core.System to get at the re-exported functions from **safe-exceptions**. As a breaking change functions by these names are no longer re-exported, and so this is a major version bump.
I'm not convinced of this wisdom of doing this, but giving us a new place in Core.Program.Exceptions to clearly document how to use exceptions properly, …
=> Specialize exception handling functions to Program monad

core-program/core-program.cabal, core-program/lib/Core/Program/Execute.hs, core-program/package.yaml, core-telemetry/core-telemetry.cabal, core-telemetry/package.yaml, core-text/core-text.cabal, core-text/lib/Core/Text/Utilities.hs, core-text/package.yaml, stack.yaml
Read no more than 1024 events at a time from the telemetry queue, which should effectively rate-limit what we're sending up to Honeycomb.
=> Limit the rate which telemetry is read from queue

core-telemetry/core-telemetry.cabal, core-telemetry/lib/Core/Telemetry/Honeycomb.hs, core-telemetry/package.yaml
The _batch_ endpoint offered by Honeycomb is allows for compressing payloads before sending. Tests using gzip to show a drop in transmitted size of around 90% for large packets of 1024 events. That's worth the CPU time :)
(they also support zstd, but gzip seems fine)
=> Compress events before sending to Honeycomb

core-program/core-program.cabal, core-program/lib/Core/Program/Arguments.hs, core-program/package.yaml, core-telemetry/core-telemetry.cabal, core-telemetry/lib/Core/Telemetry/Observability.hs, core-telemetry/package.yaml, package.yaml, stack.yaml, unbeliever.cabal
When using `complexConfig` the global options (notably the default options such as `--verbose` and `--debug` and those added by `initializeTelemetry`) were being duplicated in the generated help output. That was embarrassing.
Fixed.
=> Fix global help

core-program/core-program.cabal, core-program/lib/Core/Program/Arguments.hs, core-program/package.yaml, core-text/lib/Core/Text/Rope.hs, tests/CheckArgumentsParsing.hs
It turns out we had a fairly serious bug whereby required command-line arguments were not being assigned the correct values when there was more than one required `Argument`. Turns out internally the order dependent list of needed arguments was being reversed before the correctly ordered parameters were zipped with that list. Fixed.
=> Fix assignment of values to required arguments

core-data/core-data.cabal, core-data/lib/Core/Data/Clock.hs, core-data/lib/Core/Data/External.hs, core-data/lib/Core/Encoding.hs, core-data/lib/Core/Encoding/External.hs, core-data/package.yaml, core-program/core-program.cabal, core-program/lib/Core/Program/Execute.hs, core-program/package.yaml, core-text/core-text.cabal, core-text/lib/Core/Text/Rope.hs, core-text/package.yaml, package.yaml, tests/CheckExternalizing.hs, tests/CheckProgramMonad.hs, tests/TestSuite.hs, unbeliever.cabal
Introduce module Core.Encoding.External with a helper class Externalizing for converting data to a stable external format and parsing externally sourced data back into Haskell values.
Closes #82.
=>  Support for externalizing data

core-program/core-program.cabal, core-program/lib/Core/Program/Execute.hs, core-program/package.yaml
A problem was uncovered when invoking _ffmpeg_ using our `execProcess` helper. For some reason bytes are getting corrupted and the result was garbage audio being output! This is possibly because ffmpeg is reading stdin as well as the supplied file? We're not sure.
The solution was to change the way we close the stdin input stream for child process by switching to `nullStream` rather than `closed`.
It turns out the documentation for **typed-process** [discourages](https://hackage.haskell.org/package/typed-process-0.2.10.1/docs/System-Process-Typed.html#v:closed) the use of `closed` 
> You usually do not want to use this, as it will leave the corresponding file descriptor unassigned and hence available for re-use in the child process. Prefer `nullStream` unless you're certain you want this …
=> Fix technique used to close stdin of child process

core-program/lib/Core/Program/Threads.hs, core-telemetry/core-telemetry.cabal, core-telemetry/lib/Core/Telemetry/Observability.hs, core-telemetry/package.yaml
The Haddock links for `metric` wasn't going anywhere because Telemetry wasn't showing.
=> Fix documentation to expose Telemetry class

core-program/core-program.cabal, core-program/lib/Core/Program/Threads.hs, core-program/package.yaml
Add a new helper `forkThread_` which discards the return value (and the return Thread wrapper, more to the point) facilitating launching daemon threads.
=> Fork forever threads

core-telemetry/.gitignore, core-telemetry/core-telemetry.cabal, core-telemetry/lib/Core/Telemetry/Observability.hs, core-telemetry/package.yaml
Tried to add instances for `Telemetry (Maybe a)` and `Telemetry UTCTime`. Had troubles due to needing to bump version dependency of `core-data` to 0.3.4.0 or higher. @istathar said maybe he could fix these for me.
=> Add instances to telemetry for dates and optionals

core-telemetry/core-telemetry.cabal, core-telemetry/lib/Core/Telemetry/Observability.hs, core-telemetry/package.yaml
When resetting the trace state with `clearTrace`, don't reset the service name. As commented, the "service name" is set once per process at process startup or once with `setServiceName` and having to reset it everytime you call `clearTrace` proved annoying.
=> Preserve service name when clearing trace state

core-data/core-data.cabal, core-data/lib/Core/Encoding/External.hs, core-data/package.yaml, core-telemetry/core-telemetry.cabal, core-telemetry/lib/Core/Telemetry/Observability.hs, core-telemetry/package.yaml, stack.yaml, tests/CheckExternalizing.hs
We keep wanting to send telemetry about identifiers. While the user can convert it's supposed to be convenient, so add additional Externalize and Telemetry instances, notably UTCTime, UUID. Part of this was already done in:
- https://github.com/aesiniath/unbeliever/pull/147
=> More instances relating to identifiers

core-data/core-data.cabal, core-data/lib/Core/Data/Structures.hs, core-data/package.yaml
For some reason we missed out the `delete` functions related to HashMap and HashSet. Expose them as `removeKeyValue` and `removeElement` respectively.
=> Remove elements from Set and Map

core-data/core-data.cabal, core-data/lib/Core/Data/Structures.hs, core-data/package.yaml, core-program/core-program.cabal, core-program/lib/Core/Program/Context.hs, core-program/lib/Core/Program/Execute.hs, core-program/lib/Core/Program/Threads.hs, core-program/package.yaml, core-telemetry/core-telemetry.cabal, core-telemetry/package.yaml, core-text/core-text.cabal, core-text/package.yaml, core-webserver-servant/core-webserver-servant.cabal, core-webserver-servant/package.yaml, core-webserver-warp/core-webserver-warp.cabal, core-webserver-warp/package.yaml, package.yaml, stack.yaml, tests/CheckTelemetryMachinery.hs, tests/SimpleExperiment.hs, tests/Snippet.hs, unbeliever.cabal
Refactor the implementation of forking, waiting, and racing threads.
This is based on the ideas from the **ki** package. We attempted an implementation using that code in #149 but we ran into severe STM race conditions and had to abandon that approach.
This branch implements the idea of structured concurrency in a similar manner, providing bi-directional exception passing in the case where you have `waitThread`ed for a forked child. Here we define a "scope" as a simple Set of ThreadIds whose only purpose is to be able to cancel (kill) them if/when the scope exits. You can enter a new scope with the `createScope` function.
The mechanism that makes this work is simple use of MVars to mark the end of the the core output and telemetry processing threads (removing the craziness of them …
=> Structured concurrency re-implementation

core-program/lib/Core/Program/Threads.hs, core-program/package.yaml
The removal of `linkThread` would force upstream users to make small rewrites of their applications. This little amend will mean everything old will still compile and work, hopefully without rewrites.
`linkThread` now does nothing except maintain the legacy API for backwards compatibility. Exceptions are bidirectional so linkThread no longer needed.
=> add back `linkThread` for backwards compatibility

core-data/core-data.cabal, core-data/lib/Core/Encoding/External.hs, core-data/package.yaml, core-program/core-program.cabal, core-program/lib/Core/Program/Execute.hs, core-program/package.yaml, stack.yaml, tests/CheckExternalizing.hs, unbeliever.cabal
We previously had `queryOptionValue'` as a convenience for reading a value (notably numeric values) from a command-line option. This branch adds the a similar convenience for declared environment variables `queryEnvironmentVariable'`.
Externalize instances for Int8 and Word{8,16,32,64} are added.
=> Parse Externalizable values from environment variables

core-program/core-program.cabal, core-program/lib/Core/Program/Context.hs, core-program/lib/Core/Program/Unlift.hs, core-program/package.yaml
Nothing in this set of packages requires a MonadUnliftIO instance, but I've come across a few possible use sites where it might potentially be useful to have. **unliftio-core** is a transitive dependency for lots of things so it's not a burden to add.
=> Add MonadUnliftIO instance

core-program/core-program.cabal, core-program/lib/Core/Program/Execute.hs, core-program/package.yaml, core-telemetry/core-telemetry.cabal, core-telemetry/package.yaml
Add a check at startup to ensure that the program was linked against the threaded runtime (using the `-threaded` GHC option).
This is necessary if any FFI is happening in multiple threads (which definitely happpens in the internals of **core-telemetry** when sending data to Honeycomb) but the default assumption is that this should just work at all times. We've never tested this library without the threaded runtime and I don't ever expect to start doing so.
Closes #161
=> Ensure threaded runtime present

core-data/core-data.cabal, core-data/package.yaml, core-effect-effectful/core-effect-effectful.cabal, core-effect-effectful/package.yaml, core-program/core-program.cabal, core-program/package.yaml, core-text/core-text.cabal, core-text/package.yaml, core-webserver-servant/core-webserver-servant.cabal, core-webserver-servant/package.yaml, core-webserver-warp/core-webserver-warp.cabal, core-webserver-warp/package.yaml, package.yaml, stack.yaml, unbeliever.cabal
Updates relevant stack/cabal control files to use lts-20.10 and fixes compiler at GHC-9.2.5.
HLS 9.2.5 compatibility tested by @istathar, found acceptable.
`stack test` passes, no other explicit tests performed.
=> Use stackage lts-20.10 at GHC 9.2.5

core-program/core-program.cabal, core-program/lib/Core/Program/Context.hs, core-program/lib/Core/Program/Execute.hs, core-program/package.yaml, tests/CheckProgramMonad.hs
Introduce `changeProgram` to go from one top level type, Program τ, to another, Program υ.
This enables you to switch from a simple type when starting your application (Program None, say) to the actual user data type you intend to run at (Program Settings or whatever) once initialization is complete, thereby avoiding the hassle of needing an `mempty` value for the settings type just so you can get past `configure`.
Credit to @guaraqe who had the idea that this would be useful.
=> Enable changing application state type in sub programs

core-program/core-program.cabal, core-program/lib/Core/Program/Context.hs, core-program/lib/Core/Program/Execute.hs, core-program/package.yaml, tests/Snippet.hs
Add new action `execExternalProcess`, to wrap the _execvp(2)_ system call.
Move the output and logging semaphore MVars to the Context τ type, so that they can be used by this function to ensure the output is flushed before exec'ing.
Rename (and deprecate) `execProcess` to `readExternalProcess`.
=> Invoke (and replace with) external processes

core-program/core-program.cabal, core-program/lib/Core/Program/Arguments.hs, core-program/package.yaml
Add support top-level precis descriptions for `--help` output. Introduces `simpleConfig'` and `complexConfig'` each taking an additional parameter supplying the descriptive text to be printed above the "Usage:" section, so now you can have:
```
This is a test.
Usage:
experiment [OPTIONS] <filename> ...
Available options:
-q, --quiet    Supress normal output.
...
```
It's just cosmetic, but this catches up one of the last things that we didn't have compared to **optparse-applicative**.
=> Add top-level program descriptions to help

core-telemetry/core-telemetry.cabal, core-telemetry/lib/Core/Telemetry/Honeycomb.hs, core-telemetry/package.yaml
Support for situations where the Honeycomb host needs a tweak, such as when using
the Refinery:
https://docs.honeycomb.io/manage-data-volume/refinery/
Adding support for an environment variable `HONEYCOMB_HOST_OVERRIDE` but
still using the default 443 port, and still assuming that the host is
behind SSL.
Bump core-telemetry to v0.2.8.0
=> Allow for overriding the default honeycomb host

core-data/core-data.cabal, core-data/lib/Core/Encoding/Json.hs, core-data/package.yaml, stack.yaml
When using the Render instance (ie `writeR` or `debugR`) on a JsonValue, numbers were showing up as `200.0` even when they weren't floating point. I thought we'd fixed that, and we HAD, but for actually encoding JsonValues to Rope / Bytes! but not when Rendering.
Replicate the trick used when actually encoding in `encodeToRope` to the Render instance.
=> Render numbers properly

core-webserver-warp/core-webserver-warp.cabal, core-webserver-warp/lib/Core/Webserver/Warp.hs, core-webserver-warp/package.yaml, stack.yaml
Add a new function `launchWebserverTLS` using the facilities of **warp-tls** to allow a webserver to be launched that serves requests within a TLS connection.
=> Support TLS when launching webservers

core-text/lib/Core/Text/Utilities.hs
Another attempt to fix the Haddock links from [Render](https://hackage.haskell.org/package/core-text-0.3.8.1/docs/Core-Text-Utilities.html#t:Render). The last attempt in #174 didn't work because it's still trying to find the target module in **core-text** and not in **core-program**. Presumably it would work if the latter was in scope and imported, but it's not, so boo.
According to https://haskell-haddock.readthedocs.io/en/latest/markup.html#links the Markdown style `[text](url)` syntax should work, but when I do the Haddock generation locally it doesn't render properly.
(which is ironic given this is in a typeclass named Render)
Maybe this will work on Hackage but boo.
=> Fix forward links, again

core-program/core-program.cabal, core-program/lib/Core/Program/Arguments.hs, core-program/lib/Core/Program/Metadata.hs, core-program/package.yaml
Add information about the Git repository the software was built within available via the  TemplateHaskell `fromPackage` splice in the Version object.
=> Add Git repository information to TemplateHaskell splice

core-program/core-program.cabal, core-program/lib/Core/Program/Arguments.hs, core-program/lib/Core/Program/Metadata.hs, core-program/package.yaml
Expand the Haddock documentation concerning the `fromPackage` splice and the retrieval of the Git information fields of Version.
Simplify the code relating to the use of the symbolic `v` marker in version strings.
=> Document querying of Git repository information in fromPackage

core-telemetry/core-telemetry.cabal, core-telemetry/lib/Core/Telemetry/Observability.hs, core-telemetry/package.yaml
We've had some suggestions that _maybe_ we're getting a bit of delayed exception problems when using `encloseSpan`. The evidence is circumstantial, but it could be that the `catch ... SomeException` in Core.Telemetry.Honeycomb is at last what's actually forcing a value that was, in fact, going to bear an exception.
We know we are using the telemetry values submitted, so better to just get on with evaluating them at the use site rather than risking it for later.
=> Ensure metrics evaluated before adding

core-webserver-warp/core-webserver-warp.cabal, core-webserver-warp/package.yaml
I noticed that the documentation for **core-webserver-warp** wasn't building because **http2** has had a number of breaking changes related to error handling. Right now Stackage has 3.0 and upstream is at 4.1 so that'll be a mess at some point, but no biggie. Add a defensive upper bound on **http2** for the time being.
=> Defensive upper bound on http2 package

core-program/core-program.cabal, core-program/lib/Core/Program/Execute.hs, core-program/lib/Core/Program/Threads.hs, core-program/package.yaml, core-telemetry/lib/Core/Telemetry/Honeycomb.hs, core-webserver-warp/lib/Core/Webserver/Warp.hs, tests/Snippet.hs
A variant of `readProcess` (which gets the child's output) is `callProcess`, which just runs a child and waits for it to finish. This branch adds a wrapper around that function.
=> Enable launching child processes

core-webserver-warp/core-webserver-warp.cabal, core-webserver-warp/lib/Core/Webserver/Warp.hs, core-webserver-warp/package.yaml
The more recent **http2** packages have changed the internal error handling. In #186 we added an upper bound to avoid this, which is fine for Stackage `lts-20` and GHC 9.2 but if you want to move forward `nightly` has the more recent **http2** in it and that breaks things.
This branch removes the _incredibly cool_ use of guards to identify internal HTTP/2 problems and represent them as HTTP 4XX series response codes. Which was, as I say, incredibly cool, except that I'm not sure I've ever seen them actually appear.
When someone starts using HTTP/2 in anger against this library then we can certainly revisit this but in the mean time we'll soften the dependency on **http2** by not trying to use the error constructors that have been changing. That allows **core-webserver-warp** to build on …
=> Soften requirement of http2

core-program/core-program.cabal, core-program/lib/Core/Program/Threads.hs, core-program/package.yaml
Add new little helper function `timeoutThread` which runs a sub program with a time limit.
I'm not _entirely_ convinced that this is the right way to do this, given all the caveats listed in System.Timeout's `timeout` function, but on the other hand they rely on interrupting non-blocking I/O so presumably we would be leveraging the same thing.
=> Add timeout helper function

core-program/core-program.cabal, core-program/lib/Core/Program.hs, core-program/lib/Core/Program/Workers.hs, core-program/package.yaml
A long standing feature request has been for a mechanism to run a specified number of worker threads over a queue.
This branch introduces `runWorkers_` in new module Core.Program.Workers which runs over a TQueue and processes work as available.
(I wanted to call the function `exploitingTheWorkers` but then I'd need to add Monty Python jokes all through the library and that's already been done by another language)
=> Introduce worker threads

core-data/package.yaml, core-effect-effectful/package.yaml, core-program/package.yaml, core-telemetry/package.yaml, core-text/package.yaml, core-webserver-servant/package.yaml, core-webserver-warp/package.yaml, stack.yaml
Bump resolver to `lts-21.0` which builds against GHC 9.4.5 for testing. Tested with VS Code and **haskell-language-server** 0.2.0.0 via GHCup.
No code changes were necessary. Well done Stackage team and everyone in the Haskell community!
=> Support GHC 9.4.5

core-data/core-data.cabal, core-effect-effectful/core-effect-effectful.cabal, core-program/core-program.cabal, core-program/lib/Core/Program/Threads.hs, core-program/package.yaml, core-telemetry/core-telemetry.cabal, core-text/core-text.cabal, core-webserver-servant/core-webserver-servant.cabal, core-webserver-warp/core-webserver-warp.cabal, unbeliever.cabal
Updated the implementation of `raceThreads` to use `waitThread` internally so that exception handling (specifically re-throwing exceptions) is handled properly.
Closes #196.
=> Re-throw exceptions when racing threads

core-program/core-program.cabal, core-program/lib/Core/Program/Arguments.hs, core-program/package.yaml
There was a glitch in the order in which argument names were output in the summary part of the generated `--help` output. Fixed.
=> Fix argument summary in help output

core-program/core-program.cabal, core-program/lib/Core/Program/Execute.hs, core-program/lib/Core/Program/Threads.hs, core-program/package.yaml, unbeliever.cabal
Change `forkThread` to no longer fork the Datum object, as this had the result of silently discarding telemetry that the user thought they were adding to the in-flight enclosing span
As discussed in 
- #200 
this is not ideal, so this branch changes this built in behaviour. The major version of **core-program** is bumped to 0.7.0 by way of signalling this change.
Closes #200
=> Don't reset telemetry when forking a thread

stack.yaml
Bump resolver to lts-22.9 which builds against GHC 9.6.4 for testing. Testing with VS Code and **haskell-language-server** 2.6.0.0 via GHCup.
=> Support GHC 9.6.4

stack.yaml
Bump resolver to lts-22.23 and GHC 9.6.5.
This still requires the **HsOpenSSL** workaround in your _stack.yaml_.
=> Support GHC 9.6.5
